### ISSUE TITLE
Lombok

### ISSUE THREAD

**Issue by hcoles** [NCR-CoDE/JavaForSmallTeams#11]
Re-created from issue by @jordanjennings on gitbooks -> https://www.gitbook.com/book/ncrcoe/java-for-small-teams/discussions/2

---

This is in reference to the final section on this page:

https://ncrcoe.gitbooks.io/java-for-small-teams/content/specifics/100_know_how_to_implement_hashcode_and_equals.html

I argue that Lombok provides the cleanest and most maintainable implementations of equals and hashcode. It makes it so you literally never have to think about the implementations again. Add the annotation, and it will work as it should even if the class changes.

Also, Lombok's tooling support is really good with both Eclipse and IntelliJ at present (although both do require a small amount of setup, 1 minute effort). Perhaps it wasn't always so?

I guess I'm just saying that I'd love to see this section be a little more neutral, and mention the benefits of using Lombok while pointing out that some teams may choose not to use it due to incompatible tooling or desire to avoid any code generation tools. I'd hate for someone to get turned off from trying it out if they happen to read this section before they are familiar with it.

For me, Lombok was almost equally life-changing as Java 8 was for reducing boilerplate and writing better code. Many of the sections of this book are really well supported by Lombok features (immutable classes with @Value is one of my favorites).

Sorry for the rant 😃

Amazing book here, I agree 100% with everything else that I have read so far. I'm going to share this with my team at work.

**Comment by jbgi** [comment]
I would argue that this guide is be about Java, not Java+Lombok. To my knowledge, code that use Lombok cannot, in general, be compiled by javac, thus it is not Java code.
Most of what Lombok provides can be done through code-generating annotation processors and be 100% JavaSE compliant (JSR 269). See #7 for annotation processors that provide maintainable equals/hascode implementations through code generation at compile time.

**Comment by jordanjennings** [comment]
Lombok is a code-generating annotation processor that uses JSR 269 and is compiled by javac, so it's just an alternative to the options you listed in #7.

That said, I agree that this guide should focus on core Java. The reason I opened this post was to say that I'd like to see the reference to Lombok be more neutral. It would be reasonable to have a small section mentioning some of the popular options for code generation to handle equals/hashcode and let the reader check out the details if they are interested.

My gripe came up when reading that most people remove Lombok, which I'd say in my experience isn't true. It's anecdotal at best, and would cause people to believe that Lombok (and for that matter other compile-time code generation options) are magic that should be avoided. I think that it's just the right level of magic. It's doing things that you can easily understand, and just writes the exact code that you would be writing otherwise. It's not something like AspectJ which does some heavy duty magic.

**Comment by jbgi** [comment]
@jordanjennings are you sure about Lombok being a simple JSR 269 annotation processor?
quoting http://stackoverflow.com/questions/6107197/how-does-lombok-work/6108573#6108573

> Lombok uses a lot more than the JSR 269 api exposes. Lombok codes against a) internal javac apis and b) internal eclipse apis (in a separate processor). JSR 269 does not let you modify existing source code, but when you cast an Element to the underlying AST node, you can actually modify the AST (which is what project Lombok does)

**Comment by hcoles** [comment]
I've put together some initial material discussing the trade offs of code generators, and in fact trade offs in general.

Currently off on a branch. See -

https://github.com/NCR-CoDE/JavaForSmallTeams/commit/642240e8e4645c08390bd16f1549689eea5c7290

The mention of teams moving off Lombok has been removed, but the section still points people to consider other options before Lombok.

Hopefully this looks more balanced.

**Comment by jordanjennings** [comment]
What I can say is this: when compiling code with Oracle's JDK all you need to do is add lombok.jar to the classpath and it compiles standard Java which runs on any JVM. Although it might use internal Sun APIs, it is bootstrapped through the standard JSR 269 process.

Although it's discouraged, I know many libraries use sun's classes because the functionality they're looking for simply isn't exposed elsewhere.  Even in the [JEP](http://openjdk.java.net/jeps/260) proposing to hide the internal APIs in JDK 9 it notes that there are popularly used APIs which shouldn't be immediately removed until the functionality is properly exposed.

That said, I'm not arguing that Lombok is the "one true way" or the only solution to the problem. I can only say it has been hugely successful for me and the teams I have worked with. Like with anything there is more than one way to do it, and that's what makes the Java ecosystem so nice.

**Comment by jordanjennings** [comment]
@hcoles The new section is very helpful. I like how you have included examples to make it clear what each one looks like. I added a comment right on the commit with more detail.

**Comment by hcoles** [comment]
I've updated the branch based on every bodies comments.

Thank you for the input.

**Comment by jbgi** [comment]
:+1: it looks quite good!

**Comment by jordanjennings** [comment]
Agreed, very good changes. Thanks!
